tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "homebrew/cask-fonts"

brew "bash"
brew "jq"
brew "exa"
brew "fzf"
brew "git"
brew "neovim"
brew "starship"
brew "stow"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "go"
brew "python"
brew "sqlite"
brew "zoxide"
brew "kubernetes-cli"
brew "terraform"
brew "nvm"
brew "ripgrep"
brew "gh"

cask "kitty"
cask "slack"
cask "font-fira-code-nerd-font"
cask "goland"

