[colors]
ansi = [
  '#4d5960',
  '#e67e80',
  '#a7c080',
  '#dbbc7f',
  '#7fbbb3',
  '#d699b6',
  '#83c092',
  '#d3c6aa',
]
background = '#333c43'
brights = [
  '#4d5960',
  '#e67e80',
  '#a7c080',
  '#dbbc7f',
  '#7fbbb3',
  '#d699b6',
  '#83c092',
  '#d3c6aa',
]
cursor_bg = '#d3c6aa'
cursor_border = '#d3c6aa'
cursor_fg = '#333c43'
foreground = '#d3c6aa'

[colors.tab_bar]
inactive_tab_edge = "#1f2335"
background = "#333c43"

[colors.tab_bar.active_tab]
fg_color = "#4d5960"
bg_color = "#83c092"

[colors.tab_bar.inactive_tab]
fg_color = "#4d5960"
bg_color = "#333c43"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a7c080"
bg_color = "#292e42"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#a7c080"
bg_color = "#333c43"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#a7c080"
bg_color = "#333c43"

[metadata]
name = 'Everforest Dark (Soft)'
origin_url = 'https://github.com/frdwin/Everforest-Wezterm'
