[colors]
ansi = [
	'#4d5960',
	'#e67e80',
	'#a7c080',
	'#dbbc7f',
	'#7fbbb3',
	'#d699b6',
	'#83c092',
	'#d3c6aa',
]
background = '#333c43'
brights = [
	'#4d5960',
	'#e67e80',
	'#a7c080',
	'#dbbc7f',
	'#7fbbb3',
	'#d699b6',
	'#83c092',
	'#d3c6aa',
]
cursor_bg = '#d3c6aa'
cursor_border = '#d3c6aa'
cursor_fg = '#333c43'
foreground = '#d3c6aa'

[colors.indexed]

[metadata]
name = 'Everforest Dark (Soft)'
origin_url = 'https://github.com/frdwin/Everforest-Wezterm'
