[colors]
foreground = "#768390"
background = "#22272e"
cursor_bg = "#768390"
cursor_border = "#768390"
cursor_fg = "#22272e"
selection_bg = "#264466"
selection_fg = "#768390"
ansi = ["#545d68", "#f47067", "#57ab5a", "#c69026", "#539bf5", "#b083f0", "#39c5cf", "#909dab"]
brights = ["#636e7b", "#ff938a", "#6bc46d", "#daaa3f", "#6cb6ff", "#dcbdfb", "#56d4dd", "#cdd9e5"]
