# Nightfox Wezterm Colors
# Style: gruvfox
# Upstream: https://github.com/edeneast/nightfox.nvim/raw/main/extra/gruvfox/nightfox_wezterm.toml
[colors]
foreground = "#ebdbb2"
background = "#3c3836"
cursor_bg = "#ebdbb2"
cursor_border = "#ebdbb2"
cursor_fg = "#3c3836"
selection_bg = "#433c59"
selection_fg = "#ebdbb2"
ansi = ["#282828", "#cc241d", "#98971a", "#d79921", "#458588", "#b16286", "#689d6a", "#ebdbb2"]
brights = ["#47407d", "#f083a2", "#b1d196", "#f9cb8c", "#65b1cd", "#ccb1ed", "#a6dae3", "#e2e0f7"]

